Develop
ro-msg-angular-training/online-shop-juliaiakab pull request #1
Opened 2021-04-09 13:44 UTC by juliaiakab

I've finished the _Components_ and _Routing_ chapter tasks. @flyforfun98

2021-04-09 14:08 UTC, flyforfun98 commented on online-shop/src/app/product-details/product-details.component.css
> +    padding-left: 60px;
You can shorten the the 3 lines above by writting padding: 20px 100px 20px 60px

2021-04-12 10:06 UTC, Ducuvlad requested changes

2021-04-12 10:06 UTC, Ducuvlad commented on online-shop/src/app/components/navigation/navigation.component.css
> +  height: 3cm;
You can use px instead of cm in order to be consistent with the measuring units used.

2021-04-12 10:06 UTC, Ducuvlad commented on online-shop/src/app/components/navigation/navigation.component.css
> +}
Please order the selectors by their specificity or scope. The first ones should be general classes like h1, then specific classes ".inner", and then id selectors or more specific ones.

2021-04-12 10:36 UTC, Ducuvlad requested changes

2021-04-12 10:36 UTC, Ducuvlad commented on online-shop/src/app/products.ts
> +export const products = [
Please move this file and headers.ts to a separate directory called mockup.

2021-04-15 13:25 UTC, closed without merging